OrdererOrgs:
  - Name: Orderer0
    Domain: wizchain.net
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0.wizchain.net
        SANS:
          - localhostMSP
          - orderer0.wizchain.net
          
PeerOrgs:
  - Name: Org1
    Domain: org1.wizchain.net
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - peer0.org1.wizchain.net
        - peer1.org1.wizchain.net
    Users: 
      Count: 1
             
  - Name: Org2
    Domain: org2.wizchain.net
    EnableNodeOUs: true
    Template:
      Count: 2
      Start: 2
      SANS:
        - peer2.org2.wizchain.net
        - peer3.org2.wizchain.net
    Users: 
      Count: 1     
