version: '2'

networks:
  test:

services:

  ca_org2:
    container_name: ca_org2
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start --port 8054'
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
      - $HOME/testnet/crypto-config/fabric-ca/org2:/etc/hyperledger/fabric-ca-server
    networks:
      - test
    ports:
      - 8054:8054
