version: '2'

networks:
  test:

services:

  tls-ca:
    container_name: tls-ca
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start --port 10054'
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
      - $HOME/testnet/crypto-config/fabric-ca/tls:/etc/hyperledger/fabric-ca-server
    networks:
      - test
    ports:
      - 10054:10054
