# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  test:

services:

  ca-tls:
    container_name: ca-tls
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 10054'
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_tls
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
      - FABRIC_CA_SERVER_DEBUG=true  
      - FABRIC_CA_SERVER_CSR_HOSTS=fabric-ca
    volumes:
      - $HOME/testnet/crypto-config/fabric-ca/tls:/etc/hyperledger/fabric-ca-server
    networks:
      - test
    ports:
      - 10054:10054
      
  root_ca:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=root_ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=6054
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_CSR_HOSTS=fabric-ca      
    ports:
      - "6054:6054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --port 6054'
    volumes:
      - $HOME/testnet/crypto-config/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
    container_name: root_ca
    networks:
      - test

 
