version: '2'

networks:
  test:

services:

  org1_admin:
    container_name: org1_admin
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start --port 7054'
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
      - $HOME/testnet/crypto-config/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
    networks:
      - test
    ports:
      - 7054:7054
