NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/fabric-ca-9054-ca_ordererOrg.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/fabric-ca-9054-ca_ordererOrg.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/fabric-ca-9054-ca_ordererOrg.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/fabric-ca-9054-ca_ordererOrg.pem
    OrganizationalUnitIdentifier: orderer
