NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/fabric-ca-7054.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/fabric-ca-7054.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/fabric-ca-7054.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/fabric-ca-7054.pem
    OrganizationalUnitIdentifier: orderer
